### PR TITLE
 Fix: Height issues for Project Contributors container. #74

### PR DESCRIPTION
**Pull request by SAD0XER**
I have made some changes, please review it.

### CODE REVIEW

**Review by kunalkeshan — CHANGES_REQUESTED** [review]
## Changes Required

- Use property `"fit-content"` instead of "fitContent". Css doesn't exactly work with camel casing for its property values. 
- Add the `padding` and `height` property to the `Page` component instead of the `Contributors` component.

**Review by kunalkeshan — APPROVED** [review]
LGTM!

**Comment by SAD0XER** [comment]
Why always I made some mistakes at the en of the day? and you always fixed that in end.🤔😞

_How I ignored that **semicolon**?_

**Comment by kunalkeshan** [comment]
It's chill man. Try doing a build locally if you're not sure it will fail when making the PR. 

It will point out the error so you can fix it before pushing the changes. 

T'was a small typo, don't stress it XD

**Comment by SAD0XER** [comment]
> It's chill man. Try doing a build locally if you're not sure it will fail when making the PR. 
> 
> It will point out the error so you can fix it before pushing the changes. 
> 
> T'was a small typo, don't stress it XD

**Man, your explanation and advices are epic and so real facts.**🤩

*Thanks a lot! Actually I am learning many things from you.* 🤗

**Pull request merged**
